### ISSUE TITLE
Not working with the given example

### ISSUE THREAD

**Issue by goutam-ghosh** [Waqas-Abbasi/search-engine-api-puppeteer#1]
Hi Team,

First of all thank you for your solution of google search api
But api is giving the blank array as a result when call from chrome. 

Please help me out as soon as possible.

**Comment by Waqas-Abbasi** [comment]
Hi @goutam-ghosh 

Unfortunately, the concepts discussed in Part 2 and 3 of the article are still valid, however, the examples used to demonstrate these concepts, no longer work. This is the nature of web scrapping. If a website decides to change its class name for a certain HTML element, then the web scrapper needs to be adjusted to those class names. In the example, we used class names which Google used at the time of writing the post, however, those class names have changed since then and so the example no longer works.

However, if you follow the post and look for the updates class names in Google search results then the guide still works
